#+TITLE: About Me
#+OPTIONS: num:0

#+begin_html
  <style>
  * {
    font-size: 1.5rem;
  }
  </style>
#+end_html

~Sorry about the ugly site - just migrated from a jekyll based one to an org-page based one.~

Hello, I'm a "Data Scientist"[fn:data-scientist] at [[http://enlitic.com][Enlitic]][fn:ted-talk][fn:cnn-video], where I work with the smartest people I know applying and improving deep learning algorithms on all sorts of medical data. We're an incredibly mission-driven bunch and really want to help people - and have had pretty awesome results so far[fn:enlitic-results]. Because of all that, I consider myself one of the luckiest people around - since I get to learn a ton, work on something I love, and (hopefully) am helping make the world a better place.

To satisfy my love of learning, I am also a Master's student at the Georgia Institute of Technology studying Computer Science with a specialization in Machine Learning[fn:omscs].

* Some of the cool things I've done so far are:
1. getting first place in a Kaggle competition[fn:cause-effect-pairs], which allowed me to speak at NIPS 2013[fn:nips-talk] and meet some of my personal heroes and Machine Learning legends such as Yoshua Bengio[fn:nips-bengio], Yann LeCun[fn:nips-lecun], and Leon Bottou[fn:nips-bottou],
2. got a medal at the International Math Olympiad[fn:imo-medal] and broke a 13-year losing streak for the Philippines,
3. got the highest prize world-wide in the Interdisciplinary Contest in Modeling[fn:icm-rpi] with my awesome team,
4. was part of the Philipinnes' national youth training program ultimate frisbee team, where I got to play all over South East Asia,
5. won a whole other bunch of competitions on Machine Learning, Programming, Math, Entrepreneurship, and game-making (see my [[https://www.linkedin.com/in/diogomda][linkedin]] for more),
6. wrote a bunch of code that does all sorts of fun things (see my [[https://github.com/diogo149][github]] page).
* Everything else about me:
1. I am interested in all things Computer Science,
2. spend many weekends on Deep Learning, Hyperparameter Optimization, and a combination of the two,
3. love designing beautiful yet simple software[fn:simple-software],
5. think that Lisp syntax is the best syntax (and would love to make all sorts of Lisps when I have some time to do so),
6. love having absolutely awesome workflows and tools[fn:tools],
7. am a huge fan of open source software, try to open source everything I make, and contribute to the tools I use,
8. and love community service[fn:apo].

[fn:data-scientist] I too do not know what this means...
[fn:ted-talk] TED talk from the founder: https://www.youtube.com/watch?v=xx310zM3tLs
[fn:cnn-video] Enlitic being featured on CNN: http://money.cnn.com/2015/03/12/technology/enlitic-technology/index.html
[fn:enlitic-results] Some tasks at super-human accuracies (:
[fn:cause-effect-pairs] The cause effect pairs challenge. See [[https://www.kaggle.com/c/cause-effect-pairs][this link]] for the competition website or [[https://github.com/diogo149/CauseEffectPairsChallenge][this link]] for the source code of my solution.
[fn:nips-talk] Link of the video: [[http://videolectures.net/nipsworkshops2013_almeida_feature_engineering/][here]]
[fn:nips-bengio] I actually got to sit at his table with his lab, thanks to Isabelle Guyon, another legend that not as many people have heard off :(.
[fn:nips-lecun] We had a lively discussion about using convnets for causality to apply 2 things which we didn't understand to hopefully make something we do understand.
[fn:nips-bottou] I had a chance to have dinner with him the first night I was there and thank him in-person for teaching the [[http://cilvr.cs.nyu.edu/doku.php?id%3Dcourses:bigdata:slides:start][big data class]] online.
[fn:imo-medal] See [[https://www.imo-official.org/participant_r.aspx?id%3D17909][this link]].
[fn:icm-rpi] See [[http://approach.rpi.edu/2013/07/09/saving-the-planet-with-an-algorithm/][this link]] for a write up from my school.
[fn:apo] I was part of a community service fraternity in college - instead of partying, we just helped people. (:
[fn:tools] Most notably Emacs, archlinux, xmonad, and tmux
[fn:omscs] Specifically the [[http://www.omscs.gatech.edu/][Online Master's in Computer Science]] program
[fn:simple-software] See Rich Hickey's [[http://www.infoq.com/presentations/Simple-Made-Easy][Simple Made Easy]] talk
