#+OPTIONS: toc:nil
#+OPTIONS: num:0
#+BEGIN_EXPORT html
---
layout: post
title:  "Some Deep Learning Talks"
date:   2017-03-09
categories:
tags: ["The Art of the DL"]
---
#+END_EXPORT

Now seems like as good of a time as any to post some of the talks that I've done in the last year.

First off, my favorite! I was originally going to give a talk I had done before (hence the same title), but I had some recent inspiration about some issues in the field that I wanted to share. This was a last minute whim, and after 24 hours of neither eating nor sleeping, I finished my slides with 30 minutes to spare. The talk went great and immediately afterwards, I even had the opportunity to do a [[https://twimlai.com/twiml-talk-8-diogo-almeida-deep-learning-modular-theory-inflexible-practice/][TWiML podcast]] (thanks, Sam!). Both were surprisingly well-received, and writing the talk really helped me refine my thoughts on the field and what direction I wanted to take my work.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/-immhLHH5gM" frameborder="0" allowfullscreen></iframe>
#+END_EXPORT

Next up, one on medicine. I really enjoyed giving this talk[fn:funny] and it allowed me to share the biggest lessons from my time at Enlitic. Now that I'm seeing it after I've left, it feels almost like a summary of the time I've spent there. Summarizing those lessons helped me internalize them better, and that internalization has been incredibly helpful in conversations about the future of Medicine and Deep Learning.

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/3VpQmrj0fx4" frameborder="0" allowfullscreen></iframe>
#+END_EXPORT

This next one was incredibly fun to make, because I got to tackle the problem of explaining Deep Learning to people who were unfamiliar with it, but are excellent engineers (which is where I think I was a couple of years ago). It felt like I could make a fairly unique talk that focus hard on practical issues (something that I feel most talks do not do).

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/fvNsz7XMM9w" frameborder="0" allowfullscreen></iframe>
#+END_EXPORT

This is the last talk that I have the video of. It also was the earliest of these 4, and the only think I remember of that time was being incredibly frightened to give it. I normally don't feel that way, but the audience of this talk was much more focused towards healthcare than tech, which as a topic is somewhat out of my comfort zone[fn:thorax].

#+BEGIN_EXPORT html
<iframe width="560" height="315" src="https://www.youtube.com/embed/DGgv14_3-QE" frameborder="0" allowfullscreen></iframe>
#+END_EXPORT

[fn:funny] I generally enjoy giving talks, but it's especially pleasurable if I make it funny/playful.
[fn:thorax] I had worked a year on medical images before learning that the thorax was a human (and not just an insect) body part.
